---
title: "Prescription Merge"
author: "Martin Ueding"
date: "\\today"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tibble)
library(dplyr)

source('numeric_utils.R')
```

```{r}
ensemble <- 'cA2.09.48'
#channel <- '2pi_I2'
channel <- '3pi_I3'

workdir <- sprintf('~/Lattice/Three-Pions/projection_workdir/%s/%s', ensemble, channel)
stopifnot(dir.exists(workdir))
```

```{r}
paths <- Sys.glob(paste0(workdir, '/prescriptions/prescription_*_*.js'))
prescriptions <- lapply(paths, jsonlite::read_json)
```

```{r}
res <- list()

for (prescription in prescriptions) {
  for (frame in names(prescription)) {
    if (is.null(res[[frame]])) {
      res[[frame]] <- list()
    }
    for (irrep in names(prescription[[frame]])) {
      if (length(unlist(prescription[[frame]][[irrep]])) > 0) {
      res[[frame]][[irrep]] <- prescription[[frame]][[irrep]]
      }
    }
  }
}
```

```{r}
path_out <- paste0(workdir, '/prescriptions/all_prescriptions.js')
jsonlite::write_json(res, path_out)
```

