#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright © 2019 Martin Ueding <dev@martin-ueding.de>

import argparse
import json


def load_json(filename):
    with open(filename) as f:
        data = json.load(f)

    return data


def main():
    options = _parse_args()

    print('Loading JSON data …')
    data = [load_json(filename) for filename in options.json_file]

    print('Merging data …')
    merged = data[0]
    for d in data[1:]:
        for momentum, irreps in d.items():
            for irrep, cols in irreps.items():
                if not momentum in merged:
                    merged[momentum] = dict()
                merged[momentum][irrep] = cols

    print('Serializing to JSON …')
    with open(options.out, 'w') as f:
        json.dump(merged, f)



def _parse_args():
    '''
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    '''
    parser = argparse.ArgumentParser(description='')
    parser.add_argument('json_file', nargs='+')
    parser.add_argument('out')
    options = parser.parse_args()

    return options


if __name__ == '__main__':
    main()
