#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2019 Martin Ueding <dev@martin-ueding.de>

import json

import jinja2


def main():
    # Setting up Jinja
    env = jinja2.Environment(loader=jinja2.FileSystemLoader("."))
    template_project = env.get_template("template-slurm-project.sh")
    template_crunch = env.get_template("template-slurm-crunch.sh")

    with open('irreps_avail.js') as f:
        pairs = json.load(f)

    for momentum, irrep in pairs:
        rendered = template_project.render(momentum=momentum, irrep=irrep)
        filename = 'slurm-project-{}{}{}-{}.sh'.format(momentum[0], momentum[1], momentum[2], irrep)
        with open(filename, "w") as f:
            f.write(rendered)

        rendered = template_crunch.render(momentum=momentum, irrep=irrep)
        filename = 'slurm-crunch-{}{}{}-{}.sh'.format(momentum[0], momentum[1], momentum[2], irrep)
        with open(filename, "w") as f:
            f.write(rendered)


if __name__ == "__main__":
    main()
