---
title: "Number crunching"
author: Martin Ueding
output: html_notebook
---

```{r setup}
library(ggplot2)
library(dplyr)
library(magrittr)

theme_set(theme_light())
```

```{r utilities}
lapplyn <- function (container, f, n, ...) {
  if (n == 1) {
    result <- lapply(container, f, ...)
  } else {
    result <- lapply(container, function (x) lapplyn(x, f, n - 1, ...))
  }
  return (result)
}
```

In this document we will take the generated GEVP prescription and touch the actual HDF5 data and generate the correlators.

```{r selection}
total_momentum = c(1, 0, 0)
irrep = 'A1'

total_momentum_sq <- sum(total_momentum^2)
total_momentum_str <- paste0(sprintf('%d', total_momentum), collapse = '')

total_momentum_ref <- (if (total_momentum_sq == 0) c(0, 0, 0)
else if (total_momentum_sq == 1) c(0, 0, 1)
else if (total_momentum_sq == 2) c(1, 1, 0)
else if (total_momentum_sq == 3) c(1, 1, 1)
else if (total_momentum_sq == 1) c(0, 0, 2))
```

```{r}
prescription_filename <- sprintf('gevp-rho-%s-%s.js', total_momentum_str, irrep)
all_prescriptions <- jsonlite::read_json(prescription_filename)
```

```{r}
needed_names <- unique(unlist(lapplyn(all_prescriptions, function (rule) rule$datasetname, 7)))
```

```{r}
config_number <- 2552
base_path <- '~/Lattice/New_Projection_Test'

file_pattern <- sprintf('%s/*_cnfg%d.h5', base_path, config_number)
files <- Sys.glob(file_pattern)

diagrams <- sapply(files, function (file) strsplit(basename(file), '_')[[1]][1])
names(diagrams) <- NULL

files_list <- as.list(files)
names(files_list) <- diagrams
```

```{r}
needed_raw <- lapply(
  needed_names,
  function (datasetname) {
    #print(datasetname)
    diagram <- strsplit(datasetname, '_')[[1]][1]
    
    if (diagram == 'C4cV') {
      return (NA)
    }
    
    filename <- files_list[[diagram]]
    
    #print(sprintf('Fetching %s (a %s) from %s.\n', datasetname, diagram, filename))
    
    dataset <- rhdf5::h5read(filename, datasetname)
    if (ncol(dataset) == 2) {
      return (dataset$re + 1i * dataset$im)
    } else if (colnames(dataset)[1] == 'rere') {
      return (dataset$rere - 0*dataset$imim + 1i * dataset$reim + 1i * dataset$imre)
    } else {
      stop()
    }
  })

names(needed_raw) <- needed_names
```

```{r}
resolve <- function (prescription) {
  summands <- list(rep(NA, length(prescription)))
  
  for (i in 1:length(prescription)) {
    rule <- prescription[[i]]
    datasetname <- rule$datasetname
    diagram <- strsplit(datasetname, '_')[[1]][1]
    
    if (diagram == 'C4cV') {
      next
    }
    
    correlator <- needed_raw[[datasetname]]
    if (rule$conj) {
      correlator <- Conj(correlator)
    }
    weight <- rule$re + 1i * rule$im
    summands[[i]] <- Re(weight * correlator)
  }
  
  m <- do.call(rbind, na.omit(summands))
  apply(m, 2, sum)
}

resolved <- lapplyn(all_prescriptions, resolve, 6)
```

```{r}
resolved_filename <- sprintf('resolved-rho-%s-%s.js', total_momentum_str, irrep)
jsonlite::write_json(resolved, resolved_filename, pretty = TRUE)
```

```{r}
q_avail_actual <- names(all_prescriptions[[total_momentum_str]][[irrep]][['1']][['1']])

q_avail_actual_matrix <- apply(
  stringr::str_match(q_avail_actual, '(-?\\d)(-?\\d)(-?\\d)')[, 2:4],
  1:2,
  as.integer)

q_markus_avail_actual <- t(total_momentum_ref / 2 - t(q_avail_actual_matrix))

elements <- apply(
  q_markus_avail_actual,
  1,
  function (q) sprintf('p: %d, q: (%s), g: \\gamma_{5}, \\gamma_{5}', sum(total_momentum^2), paste0(sprintf('%.1f', q), collapse = ', ')))

df_avail_actual <- data.frame(str = q_avail_actual, element = elements, stringsAsFactors = FALSE)
```

```{r}
target_dir <- '../LuescherAnalysis/output/rho/gevps-v2/B35.32'

operator_indices_path <- sprintf('%s/rho_p%d_%s_operator-indices.tsv', target_dir, total_momentum_sq, irrep)
operator_indices <- read.table(operator_indices_path, sep = '\t', header = TRUE)

filtered <- operator_indices %>%
  filter(p_x == total_momentum_ref[1],
         p_y == total_momentum_ref[2],
         p_z == total_momentum_ref[3])
stopifnot(nrow(filtered) == 1)
operator_id <- filtered$id

gevp_indices_path <- sprintf('%s/rho_p%d_%s_gevp-indices.tsv', target_dir, sum(total_momentum^2), irrep)
gevp_indices <- read.table(gevp_indices_path, sep = '\t', header = TRUE, stringsAsFactors = FALSE)

mapping <- left_join(df_avail_actual, gevp_indices, by = c('element')) %>%
  filter(!is.na(id))
```

```{r}
correlator_matrix_indices <- expand.grid(q_source = mapping$str, q_sink = mapping$str, stringsAsFactors = FALSE)

correlator_matrix_indices %<>%
  tibble::as.tibble() %>%
  left_join(mapping, by = c('q_source' = 'str')) %>%
  rename(id_source = id) %>%
  left_join(mapping, by = c('q_sink' = 'str')) %>%
  rename(id_sink = id) %>%
  select(q_source, q_sink, id_source, id_sink)
```

```{r}
correlator_matrix_indices %<>%
  mutate(markus_file_name = sprintf('%s/rho_p%d_%s_op%d_gevp%d.%d.tsv', target_dir, sum(total_momentum^2), irrep, operator_id, id_source, id_sink))

load_target_config <- function (path) {
  target <- read.table(path, header = TRUE)
  
  target_single <- dplyr::filter(target, cnfg == config_number)
  target_single$value
}

correlator_matrix_indices$target <- mapply(load_target_config, correlator_matrix_indices$markus_file_name, SIMPLIFY = FALSE, USE.NAMES = FALSE)
```

```{r}
load_actual_config <- function (q_source, q_sink) {
  resolved[[total_momentum_str]][[irrep]][['1']][['1']][[q_source]][[q_sink]]
}

correlator_matrix_indices$actual <- mapply(load_actual_config, correlator_matrix_indices$q_source, correlator_matrix_indices$q_sink, SIMPLIFY = FALSE, USE.NAMES = FALSE)
```

```{r}
correlator_matrix_indices$time <- list(1:length(correlator_matrix_indices$actual[[1]]))
```

```{r}
correlator_matrix <- correlator_matrix_indices %>%
  tidyr::unnest() %>%
  tidyr::gather(key, correlator, actual, target)
```

```{r}
ggplot(correlator_matrix, aes(x = time, y = abs(correlator), color = key)) +
  geom_point() +
  scale_y_log10() +
  facet_grid(q_source ~ q_sink) +
  labs(title = "Comparison between Martin's and Markus' projection code",
       subtitle = sprintf('P = %s, irrep = %s', total_momentum_str, irrep),
       x = 't',
       y = expression(abs(C(t))),
       color = 'Data')

ggsave(sprintf('comparison-%s-%s.pdf', total_momentum_str, irrep), width = 10, height = 10)
```