---
title: "JSON Merge"
author: "Martin Ueding"
date: "14 August 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tibble)
library(dplyr)

source('numeric_utils.R')
```

```{r}
split_filename <- function (path) {
  filename <- basename(path)
  parts <- stringr::str_match(filename, 'resolved_(.*)_(.*)_(.*)\\.js')
  parts[1, 2:4]
}
```


```{r}
workdir <- '~/Lattice/Three-Pions/wdir_3pi_I3/'
```

```{r}
all_projected_paths <- Sys.glob(paste0(workdir, '/projected/resolved_*_*_*.js'))
```

```{r}
parts <- do.call(rbind, lapply(all_projected_paths, split_filename))
colnames(parts) <- c('total_momentum', 'irrep', 'config_number')
df <- as_tibble(parts)
df$path <- all_projected_paths
```

```{r}
recursive_merge <- function (data, config_numbers) {
  first <- data[[1]]
  
  if (is.list(first)) {
    names_first <- names(first)
    res <- list()
    for (name in names_first) {
      elements <- lapply(data, function (elem) elem[[name]])
      merged <- recursive_merge(elements, config_numbers)
      res[[name]] <- merged
    }
    return (res)
  } else if (is.vector(first)) {
    res <- do.call(rbind, data)
    rownames(res) <- config_numbers
    return (res)
  } else {
    stop()
  }
}

make_merge <- function (stuff) {
  data <- lapply(stuff$path, jsonlite::read_json, simplifyVector = TRUE)
  merged <- recursive_merge(data, stuff$config_number)[[1]]
  
  dirpath <- sprintf('%s/correlator_matrices', workdir)
  if (!dir.exists(dirpath)) {
    dir.create(dirpath)
  }
  saveRDS(merged, sprintf('%s/correlator_matrix_%s_%s.Rdata', dirpath, stuff$total_momentum[1], stuff$irrep[1]))
                          
  tibble(merged = merged)
}

result <- df %>%
  arrange(total_momentum, irrep, config_number) %>%
  group_by(total_momentum, irrep) %>%
  do(make_merge(.))
```

```{r}
merged2 <- result$merged %>%
  lapply(drop_empty)
l <- sapply(merged2, length)
result2 <- result[l > 0, ]
```

```{r}
saveRDS(result2, 'corr_matrix_3pi_I3_A40.24.Rdata')
```

```{r}
library(hadron)
```

```{r}
cfs <- result2$merged %>%
  lapplyn(function (data) { cf_orig(cf_meta(Time = ncol(data)), cf = data) }, 5)
```

```{r}
cf_boots <- lapplyn(cfs, function (cf) { bootstrap.cf(cf) }, 5)
```

```{r}
lapplyn(cfs, plot, 5)
```

```{r}
cf_boot <- bootstrap.cf(cfs[[1]][['1']][['1']][[1]][[1]], boot.l = 100)
```

```{r}
plot(cf_boot,
     main = 'A40.24; P² = 1; A2; P = -100; boot.l = 100; elem 000,000 → 000,000',
     xlab = 'Time',
     ylab = 'Correlator',
     log = 'y')
```

